#pragma once
//status board
#define STATUS_BOARD_HEIGHT 48

//windown
#define WINDOW_CLASS_NAME L"GameWindow"
#define MAIN_WINDOW_TITLE L"Super Mario Bros 3"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(0, 0, 0)
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

#define MAX_FRAME_RATE 144

#define PLATFORM 1

#define FIRE_BULLET_BBOX_WIDTH  9
#define FIRE_BULLET_BBOX_HEIGHT 9

#define FIRE_BULLET_SPEED_X	0.15f
#define FIRE_BULLET_SPEED_Y	0.05f
#define FIRE_BULLET_LIMITED_HEIGHT  10

#define FIRE_BULLET_STATE_FLYING		100
#define FIRE_BULLET_STATE_HIDDEN		200

#define FIRE_BULLET_ANI_RIGHT		0
#define FIRE_BULLET_ANI_LEFT		1